### ISSUE TITLE
Search screen hard to read on certain web browsers

### ISSUE THREAD

**Issue by terrabitz** [CONNECT-platform/codedoc#1]
# The problem

On certain web browsers, the blur effect used by the "Search the docs" button doesn't appear, making the resulting search window very hard to read. For example, on Firefox 68.7.0esr (the current built-in version that ships with Linux Debian 10.3):

![codedoc_1](https://user-images.githubusercontent.com/11320431/80143498-886f8f80-8572-11ea-9936-ffe439000dcd.png)

![codedoc_2](https://user-images.githubusercontent.com/11320431/80143537-92918e00-8572-11ea-931e-d049367fe4b3.png)

The blur works just fine on Chromium 80.0.3987.162, for example.

# Possible solution

If this is an inherent limitation of certain browsers' blur capability, it might be useful to detect whether the browser supports blurring. If it doesn't, then perhaps a simple opaque overlay could be used.

**Comment by loreanvictor** [comment]
Firefox has resolved the issue, but still offers the feature behind certain flags. For now, I increased the opacity of background when the browser does not support either `backdropFilter` or `-webkit-backdrop-filter` in its styles. In case a future update of Firefox enables this with `-moz` flag, that property should be added to the check as well.

**Comment by loreanvictor** [comment]
fix released via `@codedoc/core@0.1.30`
