### ISSUE TITLE
Nevigation on right shows only few last headings

### ISSUE THREAD

**Issue by mnn** [CONNECT-platform/codedoc#12]
I have over 150 headings on one page (automatically generated). The right navigation panel shows only few last ones (~40), cannot be scrolled to upper items and doesn't follow to upper items (headings before ~40 last ones).

![codedoc_nav_items_inaccessible](https://user-images.githubusercontent.com/1975567/83941692-9e1cd980-a7ed-11ea-9681-6bdc80a429a9.gif)

**Comment by loreanvictor** [comment]
@mnn fix deployed via `0.1.62`

**Comment by mnn** [comment]
Damn, that was fast :smile:. It works great, thank you.

**Comment by loreanvictor** [comment]
thank you for reporting, and always happy to help! B-)
