### ISSUE TITLE
Integrated Search missing

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#138]
I think [my site](http://tysonwilliams.coding.blog/) used to have [integrated search](https://codedoc.cc/#integrated-search), but I don't see it now.

Why does my site lack integrated search?

![2022-09-11_20-28-52_714_chrome](https://user-images.githubusercontent.com/34664007/189559042-fdee5c0c-41ed-46b4-bf09-d437577ee5fa.png)

**Comment by loreanvictor** [comment]
I checked [your config file](https://github.com/TysonMN/tysonmn.github.io/blob/master/.codedoc/config.tsx) and it does not look like you have [configured GitHub integration](https://codedoc.cc/docs/config/misc#github-integration), which is necessary for the integrated search (it basically uses GitHub APIs).

**Comment by TysonMN** [comment]
Ah, sorry for the trouble.  I thought I had added the search feature.
