### ISSUE TITLE
Better error message in case of missing assets on the local Dev server

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#17]
Consider this function
https://github.com/CONNECT-platform/codedoc/blob/5a74bb83f42985c1368b40b633c84e2e87e30283/src/serve/index.ts#L41-L63

but especially line 43
https://github.com/CONNECT-platform/codedoc/blob/5a74bb83f42985c1368b40b633c84e2e87e30283/src/serve/index.ts#L43

Is it correct that `'.html'` is always being appended to that file name?

I am playing around with the configuration and sometimes I get it wrong.  Here is what one of the "Not Found::" error messages looks like for me.

> \# Not Found::
> \# /generated/bundle/codedoc-bundle.js
> \# C:\Code\Blogs\tyson-williams-blog\generated\generated\bundle\codedoc-bundle.js.html

![2020-06-09_21-01-29_119_mintty](https://user-images.githubusercontent.com/34664007/84218678-85821d00-aa94-11ea-9229-3123e53188f4.png)

On the topic of error messages, where are those beautiful colors?  My error message doesn't have any red in it :(

**Comment by loreanvictor** [comment]
Yeah the error message could perhaps be improved, but appending `.html` is correct. Basically, if it was a static file it should have already been served by static middleware, so when we get to that line we are looking for an html file to serve.

P.S. what happened that you lost those colors? There is actually a good amount of work dedicated just to ensure that they would be visible!

**Comment by bender2k14** [comment]
How is it correct?  The third line of the error message says it can't find a file called `codedoc-bundle.js.html`.  Isn't it supposed to be looking for a file called `codedoc-bundle.js`?

**Comment by loreanvictor** [comment]
> How is it correct? The third line of the error message says it can't find a file called `codedoc-bundle.js.html`. Isn't it supposed to be looking for a file called `codedoc-bundle.js`?

It [does at first](https://github.com/CONNECT-platform/codedoc/blob/5a74bb83f42985c1368b40b633c84e2e87e30283/src/serve/index.ts#L39), but when it is unable to find it, [it searches for the html file](https://github.com/CONNECT-platform/codedoc/blob/5a74bb83f42985c1368b40b633c84e2e87e30283/src/serve/index.ts#L41-L45).

**Comment by bender2k14** [comment]
Oh, ok. I didn't realize that.  I was confused.

The first path is relative and the second is absolute, so I thought the second path was intended to be the absolute version of what was actually checked for the first path.  I thought that was a really good idea.  How many time have we all had some file-not-found error and the path given in the error message was relative?  Too many to count!  I am not always sure where the corresponding absolute path would be.  As a debugging technique, I create a file with a random name at the corresponding relative directory path and then find that file via a program called SearchEverything that will instantly find that file no matter where our is in my entire `C:\` drive.

What if the first line said something like this?
> Unable to find `codedoc-bundle.js`.  None of the following paths exist.

I think would help me realize that it originally looked for the file `codedoc-bundle.js` and then `became more desperate` by looking for `codedoc-bundle.js.html`.

Also, what about displaying absolute paths in both cases?

**Comment by loreanvictor** [comment]
@bender2k14 thats a good idea. will re-open the issue and rename it accordingly.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.6`
