### ISSUE TITLE
IDs for tab references

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#19]
The [tab references example](https://codedoc.cc/docs/code/refs#tab-references) shows that the `title` is both the name of the tab displayed to the user as well as the identifier that is used to reference it from another tab.

What about splitting these two responsibilities into separate attributes (or whatever they are called)?

For example, it could look like this:
```
> :Tabs
> > :Tab name=Main Thing
> > ```ts
> > import { Stuff } from './other-thing';      // @see tab:other
> > import { MoreStuff } from './other-thing';  // @see [le source](tab:other)
> > ```
>
> > :Tab name=Other Thing id=other
> > ```ts
> > export const Stuff = 2;
> > export const MoreStuff = 3;                 // --> bet you expected more from this code sample didn't ya?
> > ```
```

The tooltip for `// @see tab:other` would still be `See Other Thing` because the default behavior would still be to display the name of the tab.

I see three advantages with this approach.
1. The existence of the `id` attribute communicates the intention in the source code that a tab is being referenced from other tab.
2. The name of the tab can be changed without needing (and possibility forgetting) to also change all the references.
3. The name of the tab might be long, but the ID could be very short, which can help improve readability.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.6`
