### ISSUE TITLE
Page links not selectable on certain browsers

### ISSUE THREAD

**Issue by terrabitz** [CONNECT-platform/codedoc#2]
# The problem

It looks like there are some weird behaviours with the page-level links on certain browsers. On Chromium 80.0.3987.162, the links are either unclickable or clickable only in very specific parts of the element:
![codedoc links issue](https://user-images.githubusercontent.com/11320431/80148149-39c5f380-857a-11ea-9f41-96cd3ea9649a.gif)

In Firefox 68.7.0esr, the links work just fine:

![codedoc links issue 2](https://user-images.githubusercontent.com/11320431/80148200-4b0f0000-857a-11ea-9c76-762fefe1831f.gif)

**Comment by loreanvictor** [comment]
Unable to reproduce it on MacOS 10.14.4 (Mojave) Chrome 81.0.4044.122. Could you check if updating chrome resolves your issue?

**Comment by terrabitz** [comment]
@loreanvictor Hmm, it's very peculiar. I just tried testing this with a bunch of browsers from BrowserStack, and I can't reproduce it either (even on old Chrome versions). I guess this is a Chromium-specific issue.
