### ISSUE TITLE
Make build call install

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#27]
There is a particular design aspect of the .NET Core CLI that I like.  By default,
- executing [`dotnet build`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build) implicitly executes [`dotnet restore`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore) and
- executing [`dotnet publish`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) implicitly executes `dotnet build`.

I like this API because I think it makes it easier to achieve the behave the user actually wants.  I prefer this behavior when I am manually executing commands.

But sometimes it can be helpful to execute a build without a restore or a publish without a build.  This is possible by executing
- `dotnet build --no-restore` and
- `dotnet publish --no-build` (which implicitly sets `--no-restore`).

I prefer this behavior when doing automated builds, because when some part fails, I think it is easier to determine what part failed.

What about changing the codedoc CLI to behave similarly?

**Comment by loreanvictor** [comment]
which commands do you think should implicitly execute each other?

**Comment by bender2k14** [comment]
It is already halfway there because `codedoc serve` implicitly calls `codedoc build`.  (So I will correct the title, which suggested that this was not the case.)

I would like `codedoc build` to implicitly call `codedoc install`, but it currently does not.  Then this will never happen to a user.

```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (temp)
$ codedoc build

# Error: your local codedoc installation is incomplete.
# There are some packages missing from .codedoc/node_modules
# - Run codedoc install to install them.
# - Or run codedoc update to install the latest version.


twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (temp)
$ codedoc install

# Installing local packages required by codedoc ...
npm WARN .codedoc No description
npm WARN .codedoc No repository field.
npm WARN .codedoc No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 580 packages from 478 contributors and audited 582 packages in 14.275s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (temp)
$ codedoc build

# Building ...
# Fetching project configuration ...
# building ........ src\markdown\404.md
# built:: ......... dist\404.html
# building ........ src\markdown\index.md
# built:: ......... dist\index.html
# building ........ src\markdown\sample-blog-post.md
# built:: ......... dist\sample-blog-post.html
# building ........ src\assets\styles\codedoc-styles.css
# built:: ......... src\assets\styles\codedoc-styles.css
# building ........ src\assets\bundle\codedoc-bundle.js
# built:: ......... src\assets\bundle\codedoc-bundle.js
# Build Successful.
```

**Comment by loreanvictor** [comment]
> I prefer this behavior when doing automated builds, because when some part fails, I think it is easier to determine what part failed.

You mostly only need to use `codedoc build` in automatic builds / deploy scripts rather than on your local machine though. As you mentioned, this means having the commands be separated would be actually more useful for debugging, and since this isn't a command that is commonly used manually, there wouldn't be any ergonomic gain in merging the two commands as well.

**Comment by bender2k14** [comment]
I agree with all that.

If you did decide to do this though, `codedoc serve` would only need to call `codedoc build --no-install` (or whatever).

**Comment by loreanvictor** [comment]
`codedoc serve` doesn't directly call `codedoc build`, it rather invokes the `build()` function from `@codedoc/core` library (alongside `rebuild()` for iterative rebuilding).
