### ISSUE TITLE
This project should get added to StaticGen 

### ISSUE THREAD

**Issue by terrabitz** [CONNECT-platform/codedoc#3]
I think this project should get added to Netlify's StaticGen indexer for static site generators: https://www.staticgen.com/

It looks like it passes [all the requirements](https://www.staticgen.com/contribute)

**Comment by loreanvictor** [comment]
@terrabitz thanks for the suggestion! I created [the pull request](https://github.com/netlify/staticgen/pull/778), will close this issue when it is resolved.
