### ISSUE TITLE
Correctly link to Light/Dark image

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/codedoc#32]
Currently the dark and light images in the `DarkLight` component are not ordered properly, as a result opening the image link will get weird results (opening the dark-mode image when in light mode and vice-versa).

It should be fixable by simply adding a higher `z-index` property to the visible div.

https://github.com/CONNECT-platform/coding-blog/issues/19

**Comment by bender2k14** [comment]
There is similar but different behavior with [coding-blog-boilerplate](https://github.com/CONNECT-platform/coding-blog-boilerplate).

The banner image on the main page correctly varies based on light vs dark mode.  However, for both modes, the link obtained when selecting "Copy image address" is `http://localhost:3000/coding-blog-boilerplate/img/cb-banner-dark.svg`.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.6`
