### ISSUE TITLE
Headings anchors are too big

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#35]
For a heading on GitHub, the anchor tag is only on the link image to the left of the heading.  This can be seen in the gif below by the fact that the cursor is a pointer unless it hovers over the link image where it becomes a hand with the index finger extended.  This makes it possible to select the heading and copy it (e.g. in the image below, that would be putting "GitHub" on the clipboard).

![GitHub](https://user-images.githubusercontent.com/34664007/85483096-d6f8d480-b589-11ea-8cfb-1c15e75ff2ac.gif)

In contrast, for a site made with CODEDOC, the anchor tag spans the same width as the heading.  This can be seen in the gif below by the fact that the cursor is a hand with the index finger extended the entire time that the link image is displayed.  If I would have tried to select the heading for the purpose of copying it (i.e. to copy "Usage"), then the link to the heading would be put on the clipboard instead.

![CODEDOC](https://user-images.githubusercontent.com/34664007/85483356-4242a680-b58a-11ea-840c-52b1867bea14.gif)

This behavior is particularly weird when the user wants to put their own anchor tag in the heading.  Then clicking the heading first copies the link to the clipboard and then follows the link.

![2020-06-23_19-59-39_141](https://user-images.githubusercontent.com/34664007/85484369-538cb280-b58c-11ea-99b0-a2e557ada2e3.gif)

I prefer the way that heading anchors work on GitHub.

Can CODEDOC be changed to create headings with anchors like those on GitHub?

**Comment by loreanvictor** [comment]
This is deliberate. The idea is that the main interaction (by a large margin) with a heading element is to copy its link, as it is used as a reference to a particular segment of the content. The current implementation optimizes that interaction (specifically on mobile devices and tablets) at the expense of some other interactions (like copying heading's text or embedding other links in the heading).

With further usage of **CODEDOC**, however, that might be changed. For example if usage data indicates that the main interaction is something else, or that the other interactions are common enough to deserve some UX attention.

P.S. this is only the default behavior. The role of **CODEDOC** is to ensure a bare minimum quality of UI/UX for projects using it out of the box, not enforcing such decisions. For example, you can [override the default heading component](https://github.com/CONNECT-platform/marked#overriding-components) and replace it with one that suites your preferences / particular needs for your projects (and I've tried to make sure that process is convenient and easy).
