### ISSUE TITLE
How to override default CSS

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#36]
I obtained the following screenshot from [this page](https://tysonwilliams.coding.blog/sample-blog-post) on my site.

![2020-06-23_20-21-00_143_chrome](https://user-images.githubusercontent.com/34664007/85486265-f09d1a80-b58f-11ea-938a-58b02bdefe3f.png)

I didn't expect there to be any white.  There is no white in the demo of dark mode on [utterances](https://utteranc.es/).

![2020-06-23_20-20-42_142_chrome](https://user-images.githubusercontent.com/34664007/85486361-1d513200-b590-11ea-9770-682218a6a01f.png)

Is this a bug with CODEDOC or utterances?

**Comment by bender2k14** [comment]
Ah, someone reported the same issue against utterance
https://github.com/utterance/utterances/issues/290

**Comment by bender2k14** [comment]
Quoting https://github.com/utterance/utterances/issues/290#issuecomment-648653046
> So simply adding a css rule to give the `<iframe>` element a `transparent` background should solve it.

Yes, I figured out that much last night as well.  If I add the CSS
```
iframe {
  background: transparent
}
```

to the bottom of `styles/codedoc-styles.css`, then the problem is fixed.

How do I have CODEDOC put this CSS into this generated file?

**Comment by loreanvictor** [comment]
`styles/codedoc-styles.css` includes all styles for **CODEDOC** components, so you can simply [add some styling for your component](https://codedoc.cc/docs/markdown/custom-components#component-code). Using component style is the recommended way as well since it ensures this style is only affecting this particular component and not all `<iframe>`s on the page.

Besides that, you can also [add global scripts and stylesheets](https://codedoc.cc/docs/config/page#scripts-and-stylesheets).

**Comment by bender2k14** [comment]
Is the problem line 153?
https://github.com/CONNECT-platform/codedoc/blob/cdb1b5937b397b1a1a9208bc6c2fcb72c2d5dd95/src/components/page/style.ts#L149-L155

Can that be removed?

**Comment by loreanvictor** [comment]
That is a default styling to ensure that the typical `<iframe>` fits in well with the rest of the content, while also preserving its own intended style.

**Comment by bender2k14** [comment]
I plan to change to a more targeted solution, but first I just wanted to get something working.

I wanted to try the global approach first, but it is not as global as I expected.
```tsx
stylesheets: [
  <style>{`
    iframe {
      background: transparent
    }
  `}</style>
]
```

My global styling got added before the styling by CODEDOC, so the CODEDOC styling overrode my styling.

![2020-06-24_11-51-16_147_chrome](https://user-images.githubusercontent.com/34664007/85598753-81680a80-b611-11ea-92d0-ef5ae18d2b92.png)

Is this the intended behavior?

**Comment by loreanvictor** [comment]
Sort of. Basically the component styles are added after the page is processed (so that all components are collected from the page), while these styles are injected while the page is being generated. Since this behavior means you need to be a bit more specific with global CSS (which is generally not the recommended method anyways), I kept it around.

This means, in your case, being a bit more specific should do the trick, for example perhaps changing the style selector to `iframe.utterances-frame` or `.utterances iframe`.

If you really want to override the styles, you can add your style element directly to `.codedoc/content/index.tsx` (first thing inside the `<Page>` component).

**Comment by bender2k14** [comment]
Yes, using `iframe.utterances-frame` worked from that global location.  I will make it more specific later.

One last thing.

How is line 153...
https://github.com/CONNECT-platform/codedoc/blob/cdb1b5937b397b1a1a9208bc6c2fcb72c2d5dd95/src/components/page/style.ts#L149-L155

...consistent with 

> [Integrated Dark Mode](https://codedoc.cc/#integrated-dark-mode)
> Its 2020, and dark-mode should be considered a universal right! Codedoc supports dark-mode on all your docs.

A universal right for all HTML elements except `iframe`?  ;)

Is it because `iframe` is not considered a "doc"?

**Comment by loreanvictor** [comment]
> A universal right for all HTML elements except `iframe`? ;)
> 
> Is it because `iframe` is not considered a "doc"?

:))))

`iframe` also has that right, unfortunately it falls out of **CODEDOC**'s jurisdiction though. many websites do not even support the OS preference, I believe a good portion of operating systems don't even have such a preference, and there is no standard method for communicating **CODEDOC**'s user preference (which can be set despite lack of OS support) to `iframe`s. as a result, changing `iframe`'s background based on dark mode often times results in content of the `iframe` not being readable. that is also why the default background is white, in case a website has not set any background color but have assumed a white background (which is the default behavior).

**Comment by bender2k14** [comment]
Thanks for all these thorough answers.  I am learning a lot from you! :)

**Comment by bender2k14** [comment]
I got a local solution working with this code in the `index.tsx` files of my custom component.

```tsx
return <div>
         <style>
          {`
            iframe.utterances-frame {
              background: transparent
            }
          `}
         </style>
         <script src='https://utteranc.es/client.js'
                 {...attributes}
                 async />
       </div>
```

My attempts to move the style to a `style.ts` file as shown in the [custom component documentation](https://codedoc.cc/docs/markdown/custom-components#component-code) all failed :(

**Comment by loreanvictor** [comment]
@bender2k14 that is not a local solution. You are basically adding a redundant style element per component instance, which is generally not a good idea.

Why your attempts for using component styles failed? Perhaps I could assist on that front.

**Comment by bender2k14** [comment]
Thanks for offering to help :)

I will describe my most recent attempt, which is also available in [this branch](https://github.com/bender2k14/tyson-williams-blog/tree/transparent_iframe_via_css).

I am trying to follow the example in the [Custom Component documentation](https://codedoc.cc/docs/markdown/custom-components).  To avoid introducing problems, I only changed things if I thought it was necessary.  So the name "card" is still used in some places.

This approach doesn't work.  The `background` of the `iframe` in question is still `white`.

Here is my `style.ts`
```ts
import { themedStyle } from '@connectv/jss-theme';
import { CodedocTheme } from '@codedoc/core';


export const CardStyle = themedStyle<CodedocTheme>(theme => ({
card: {
   'iframe.utterances-frame': { background: 'transparent' },
 }
}));
```

Here is my `index.tsx`
```tsx
import { ThemedComponentThis } from '@connectv/jss-theme';
import { RendererLike } from '@connectv/html';
import { CodedocTheme } from '@codedoc/core';

import { CardStyle } from './style';


export interface UtterancesOptions {
  theme: string;
}


export function Utterances(
  this: ThemedComponentThis,
  options: UtterancesOptions,
  renderer: RendererLike<any, any>,
) {
  const classes = this.theme.classes(CardStyle);
  let theme = 'github-light';
  if (options && options.theme && options.theme !== '') theme = options.theme;
  const attributes = {
    'repo': 'bender2k14/tyson-williams-blog',
    'issue-term': 'pathname',
    'label': '💬comments',
    'theme': theme,
    'crossorigin': 'anonymous'
  }
  return <div class={`${classes.card}`}>
           <script src='https://utteranc.es/client.js'
                   {...attributes}
                   async />
         </div>
}
```

**Comment by loreanvictor** [comment]
I suspect changing your `style.ts` to this would work:

```ts
import { themedStyle } from '@connectv/jss-theme';
import { CodedocTheme } from '@codedoc/core';


export const CardStyle = themedStyle<CodedocTheme>(theme => ({
  card: {
     '& iframe.utterances-frame': { background: 'transparent' },
   }
}));
```

According to [JSS docs for nested selectors](https://cssinjs.org/jss-plugin-nested?v=v10.3.0).

**Comment by bender2k14** [comment]
Yes, that works.  I have never seen this before.  Thanks for the help! :D

**Comment by loreanvictor** [comment]
Yes JSS takes a bit of getting used to, since it looks a lot like CSS but you need to constantly remind yourself that its actually just JS ;-)
