### ISSUE TITLE
Improved favicon support

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#38]
If the user provides a path to a favicon in the config...
https://github.com/CONNECT-platform/codedoc/blob/88d00dbb58472a0b256422c74a852782716ed6c1/samples/config.ts#L21-L23

...then CODEDOC adds the following `link` element...
https://github.com/CONNECT-platform/codedoc/blob/cdb1b5937b397b1a1a9208bc6c2fcb72c2d5dd95/src/components/page/index.tsx#L40

...to the `head` element.

A web programmer friend of mine recommended [RealFaviconGenerator](https://realfavicongenerator.net/).  Maybe there are a hundred sites like this; I am still new to this.

For what it's worth though, RealFaviconGenerator thinks there are many opportunities for [codedoc.cc](https://codedoc.cc/) to improve its use of favicons.  Here is the [report](https://realfavicongenerator.net/favicon_checker?protocol=https&site=codedoc.cc%2F#.XvOqMihKj7w).

Given a master image (with size 260x260 or more), [these instructions](https://realfavicongenerator.net/favicon_result?file_id=134f3fd6b63a197975c6918ae92fc9471df85759&technology=node_cli#.XvOuiihKj7w) show how to use the npm package `cli-real-favicon` to generate all the various image files and then modify any HTML to correctly reference those images.

Is there any desire for CODEDOC to take this on as a dependency to step up its favicon game?

Or would it be more appropriate to make a plugin for CODEDOC that utilizes ReadFaviconGenerator?

**Comment by loreanvictor** [comment]
There is one particular error in the report pertaining to icon of pinned tabs on Safari. Safari however seems to have no problem with pinning [codedoc.cc](https://codedoc.cc).

Besides that, the rest of the issues are about the resolution of the icon when you add it to your home screen. Since this is not the typical usage for websites generated by **CODEDOC**, I would say it falls out of core functionality and would be better suited for a plugin.

**Comment by bender2k14** [comment]
Oh, RealFaviconGenerator doesn't seem like such a good choice to me anymore.  [Its GitHub repo](https://github.com/RealFaviconGenerator/realfavicongenerator) only has two commits from seven years ago.

**Comment by bender2k14** [comment]
Humm...that was only one of the repos in [that GitHub organization](https://github.com/RealFaviconGenerator).  Other repos were updated more recently.
