### ISSUE TITLE
Nested sidebar items

### ISSUE THREAD

**Issue by UberMouse** [CONNECT-platform/codedoc#4]
I would like to be able to nest sidebar items at least one extra level. I don't think there is currently a way to do this but I might be wrong.

ie

```
toplevel/
  some-article
  sublevel/
     some-other-article
```

**Comment by loreanvictor** [comment]
There is. You can simply use the [`:Collapse`](https://codedoc.cc/docs/markdown/collapse) component in the sidebar, which can be nested as many times as you want it.

So for the example you provided, the content of `_toc.md` would look something like this:

```md
> :Collapse label=toplevel
>
> [some-article](/some-article)
> > :Collapse label=sublevel
> >
> > [some-other-article](/some-other-article)
```

**Comment by UberMouse** [comment]
Ah yes, I see now. It would be helpful to provide an example like that in the documentation, I tried that format but didn't realize you needed two `>` characters.

Thanks :)

**Comment by loreanvictor** [comment]
sure thing! I just updated [this section](https://codedoc.cc/docs/overview#table-of-contents) on the overview page adding an example of nested collapses and added [this section](https://codedoc.cc/docs/markdown/collapse#table-of-contents) to documentation of collapse component specifically for that (you might need to hard-refresh the docs to see the changes).
