### ISSUE TITLE
Permalink for code lines and line ranges

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/codedoc#40]
Since GitHub introduced this feature, I find myself constantly using it for referencing code. I suspect it will be exceedingly useful in CODEDOC as well to be able to reference specific parts of code snippets via permalinks. At least, some form of permalink per snippet seems like a basic necessity now. Perhaps both should be implemented?

**Comment by bender2k14** [comment]
I completely agree.  I was considering creating the same issue, but I didn't know how realistic it would be to implement.  I find it extremely useful to link to specific lines of code on GitHub.

To give an example involving CODEDOC, for [this line in my repo's README](https://github.com/bender2k14/tyson-williams-blog#user-content-additional:~:text=If%20port%203000%20is%20being%20used%2C%20then%20a%20different%20one%20can%20be%20specified%20in%20the%20configuration.), I wanted to link to lines 47 to 49, which are
```
  dev: {
    port: 3000                           // --> the port for local dev server
  },
```

Instead, I linked to the previous heading.

**Comment by loreanvictor** [comment]
For specific lines in code snippets it should be fairly simply. Each line has a line-counter element that can receive an ID and then have a copy-link behavior similar to headings.

Line-ranges might take up a bit more work, but not a lot. I suspect expected behavior would be scrolling to the first line of the range. As for highlighting lines in the range, the copy functionality could also check the already selected line-ranges and add them to some query string on the link, which is then parsed by the page on load (and should get removed when the lines are deselected). This strategy might even allow for permalinks of multiple ranges of lines (instead of one), which can also be useful (highlighting particular aspects of a particular code-snippet and showing it to other people).

**Comment by loreanvictor** [comment]
ok also [added this to the docs](https://codedoc.cc/docs/code/links) since authors can do fun stuff with it (having buttons highlight parts of a code snippet, for example).

deployed via `0.2.9`.
