### ISSUE TITLE
One pixel shear just above footer bar

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#42]
I see an approximately one pixel shear just above the bar in the footer when using
- Google Chrome 83.0.4103.106 with OS
- Android 7.0 and hardware
- [LG K20V VS501](https://www.amazon.com/dp/B079P5QGPP).

I put a red rectangle around it in the screenshot below.
![86187090-9c9ab480-bb00-11ea-910f-6238b2a5deb8](https://user-images.githubusercontent.com/34664007/86265059-efb84a00-bb88-11ea-838c-4491c96f3044.png)

**Comment by loreanvictor** [comment]
My guess would be this is due to the blurring of the footer's background, perhaps Chrome uses some approximation mechanism for that which affects a small area above the blurred region as well?

**Comment by bender2k14** [comment]
Ok, I see what you mean now.  Here is a similar screenshot from an Google Chrome on an iPhone 10.
![IMG_20200701_104729](https://user-images.githubusercontent.com/34664007/86264942-c5ff2300-bb88-11ea-893e-d474aefcb07f.png)

**Comment by bender2k14** [comment]
I updated my original comment with more detailed information in case this issue is passed upstream.

**Comment by loreanvictor** [comment]
Yes I suspect this issue should be reported [here](https://bugs.chromium.org/p/chromium/issues/list). @bender2k14 since you have faced the issue on your system, could you open an issue there and link it here? I am personally unable to reproduce this on my machine so wouldn't be able to provide further details (if needed) if I opened the chromium issue.

**Comment by bender2k14** [comment]
Done.  Thanks for telling me where to create the issue.  That was very helpful :)
https://bugs.chromium.org/p/chromium/issues/detail?id=1101862

**Comment by loreanvictor** [comment]
Thanks a lot! Will keep this issue open to monitor the status of the [external issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1101862). Though it really seems any issue pending on some external source is taking way longer to resolve unfortunately (hopefully the label helps with sorting through them).

**Comment by loreanvictor** [comment]
closing this as pending issue is closed due to inactivity.
