### ISSUE TITLE
List of internal redirects

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#47]
I expect that I will eventually want to "change" publically available URLs to my site.  Either I will have a typo in some URL or want to change the structure.

Is there a way to specify a list of internal redirects?

As a hypothetical example, I would want to
- redirect `https://tysonwilliams.coding.blog/this_is_speled_correctly`
- to `https://tysonwilliams.coding.blog/this_is_spelled_correctly`

**Comment by loreanvictor** [comment]
It is not possible right now. Its a pretty good suggestion, though it is not directly related to **CODEDOC** (as redirects are properties of hosting environment not build tools), but [`coding.blog`](https://github.com/CONNECT-platform/coding-blog). Created a [corresponding issue](https://github.com/CONNECT-platform/coding-blog/issues/20) there.
