### ISSUE TITLE
Incremental rebuilds are stopped in case of error

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#48]
While `codedoc serve` was running, I created the code block...
> \`\`\`C#
> \`\`\`

...and then saved.  Initially I received the error message
```
Language does not exist: C#
```

After a delay of a few seconds, I received this error message
```
Error:
 #
 # Unrecognized Language:: C#
 #
 # Check https://prismjs.com/#supported-languages for a list of supported languages.
 # You can also add --safe-highlight flag to snippets with unsupported langauges.
 #
    at Object.Code (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@codedoc\core\src\components\code\index.tsx:53:22)
    at ComponentPlugin.create (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\html\src\renderer\plugin\component\component.ts:39:25)
    at C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\html\src\renderer\extensible-renderer.ts:45:77
    at Array.some (<anonymous>)
    at ExtensibleRenderer.create (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\html\src\renderer\extensible-renderer.ts:45:18)
    at Parser.tok (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\marked\src\parser.tsx:75:16)
    at Parser.parse (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\marked\src\parser.tsx:34:28)
    at C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@connectv\marked\src\index.ts:13:19
    at Object.<anonymous> (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@codedoc\core\src\build\content.tsx:19:36)
    at step (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@codedoc\core\dist\es5\build\content.js:44:23)
[ERROR] 20:50:35 Error:
 #
 # Unrecognized Language:: C#
 #
 # Check https://prismjs.com/#supported-languages for a list of supported languages.
 # You can also add --safe-highlight flag to snippets with unsupported langauges.
 #
```

After this, there was no longer any incremental rebuilds.

I expected that incremental rebuilds would continue.

The URL https://prismjs.com/#supported-languages in the error message was very helpful.  It helped me realize that I should replace `C#` with `csharp`.  If I make this kind of mistake again, I hope this URL is provided and incremental rebuilds continue working.

**Comment by loreanvictor** [comment]
This is not limited to choice of language. You can get the same issue if you mis-type the name of a component, have issues in LaTeX syntax, etc.

This issue is risen due to tiered watching process. Basically, the main build process is in charge of watching markdown files for issuing rebuilds, so when there are errors it will stop and hence cannot react to changes in markdown files. Historically this was all done on a separate process, thats why the main build process doesn't have proper error-handling in place to mitigate that issue.

Will fix this asap. In the meanwhile, when you get an error, you can save one of `.codedoc/*.ts` files so that the outer watcher process picks up changes and starts rebuilds.

**Comment by bender2k14** [comment]
> Will fix this asap.

Thanks! :)

> In the meanwhile, when you get an error, you can save one of `.codedoc/*.ts` files so that the outer watcher process picks up changes and starts rebuilds.

My workaround is to kill the process with `Ctrl+C` and then restart it.

**Comment by loreanvictor** [comment]
as it turns out, the initial build process could fail in case of error as well, and in such a case we would need to actually restart the process, as otherwise we would have a weird bundle with lots of components missing. anyways that should also be fixed now.

**Comment by bender2k14** [comment]
I will test when a new version is released.  [Latest version of `core`](https://www.npmjs.com/search?q=codedoc%2Fcore) is still `0.2.6` from 22 days ago.

**Comment by loreanvictor** [comment]
> I will test when a new version is released. [Latest version of `core`](https://www.npmjs.com/search?q=codedoc%2Fcore) is still `0.2.6` from 22 days ago.

yes its not released yet. I'm going to release it ideally today or tomorrow alongside bunch of other changes and bug fixes.

**Comment by bender2k14** [comment]
I am in no hurry

**Comment by bender2k14** [comment]
Works perfectly!  Great job :)
