### ISSUE TITLE
build files in git and Github Pages

### ISSUE THREAD

**Issue by LukasForst** [CONNECT-platform/codedoc#5]
Hi,
I like your work, awesome job! I wanted to setup a simple blog with my code and I noticed that `node_modules` have to be commited in the repo, which is something that I don't like (at least because of the size of the repo).

As I'm using Github Pages to host the blog I created Github Action pipeline, that takes the repo without `node_modules`, builds it and deploys it to the separate branch `gh-pages`. The benefit is that you don't have `node_modules` and `html` files, that are automatically generated, in your source code, but rather in the separate branch.

I think it is an elegant solution, so I just wanted someone know, that it is possible not to commit `node_modules` to the repo and utilize github actions instead.

* [Repo](https://github.com/LukasForst/blog)
* [config.ts](https://github.com/LukasForst/blog/blob/master/.codedoc/config.ts)
* [pipeline](https://github.com/LukasForst/blog/blob/master/.github/workflows/deploy-to-gh-pages.yml)

**Comment by loreanvictor** [comment]
while you do need to have the html files on GitHub somehow (either on the master branch or on the gh-pages branch), you definitely DO NOT NEED the `node_modules` to be there. [This is the repo for the documentation for codedoc](https://github.com/CONNECT-platform/codedoc-docs), built using codedoc itself, and [this is another example](https://github.com/CONNECT-platform/coding-blog) built using codedoc and hosted on GitHub pages, both on master branch, none having `node_modules` (or `.codedoc/node_modules`) on the repo.

that said, using GitHub Actions to not have the `html` files directly on the master branch itself is a pretty nice idea. I have been meaning to get around to it but couldn't find the time (I mean codedoc itself is just released less than a week ago), so looking forward to see it in action (and using your solution)! I'll modify the issue title to properly reflect that (from `node_modules in git and GitHub Pages` to `build files in git and GitHub Pages`), and will keep the issue open for now awaiting your solution using GitHub Actions.

**Comment by loreanvictor** [comment]
[this solution](https://github.com/CONNECT-platform/codedoc/issues/5#issue-608594736) resolves the issue completely. keeping it open until it is also added to the official documentation.

**Comment by LukasForst** [comment]
Agggr, you're right about `node_modules`, my bad, I'm **not** _frontend dev_, sorry! 

About the - `cd .codedoc && npm install`, I think that, in this case, the version of all libraries including `codedoc` remains same as during the local development thanks to the `package-lock.json`. Whereas using `codedoc update` can result in updating the libraries, no? If this is the case, I would propose to stick with `npm install` as if the pipeline would update libraries, it can potentially change some behavior or break something. However, if the commands are equal in terms of updating libraries, it is probably better to use `codedoc update`.  (again, not frontend developer, so not sure whether I got this right)

**Comment by loreanvictor** [comment]
thats a good point, so lets keep it as is. since that affects people collaborating on some documentation together as well, I think for convenience I'll add an `install` command to CLI as well, which will just install packages instead of updating everything.

**Comment by loreanvictor** [comment]
it turns out there was a race condition for creating the `assets` folder which sometimes caused some assets not to be created during the build process. should be fixed by [this](https://github.com/CONNECT-platform/codedoc/commit/030dd40544f1d5dbc9dc3426e0b510d290f3b75b), deployed via `@codedoc/core@0.1.36`

**Comment by loreanvictor** [comment]
added [this section](https://codedoc.cc/docs/config/output#build-files-on-git) to official docs as well for how to achieve this. again, @LukasForst thanks for the neat solution!

**Comment by LukasForst** [comment]
Thanks! One last thing, you misspelled my name 😄, no biggie though
> proposed by Lukas Frost, is to put all

should be 

> proposed by Lukas Forst, is to put all
