### ISSUE TITLE
Improve rendering of warning/error code underlining

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#53]
The ability to mark sections of code as though they have a compiler warning or error was recently added (c.f. https://github.com/CONNECT-platform/codedoc/issues/49).  This is a great improvement, and I am already using it [here](https://tysonwilliams.coding.blog/2020-07-14_identity_as_as#code6-l1) and [here](https://tysonwilliams.coding.blog/2020-07-14_identity_as_as#code9-l5).  (Side note: Those links are the new links to specific lines of code.  Sometimes they are causing the browser to scroll to the correct spot, but most of the time it comes up short for me.  Is that expected?)

There is some room for improvement with the underlining.  The main issue is the length.  I excluded the last letter "e" by [writting](
https://github.com/bender2k14/tyson-williams-blog/commit/4872695404896b7870c35db320e626cf379d464a#diff-8613670eee9d7a377699fb660adc1d24R109)...
```
new Dictionary<int, int>()./*~err~*/TryGetValu/*~err~*/e(0);
```

...and the result looks ok.  If I had included the "e" by writing...
```
new Dictionary<int, int>()./*~err~*/TryGetValue/*~err~*/(0);
```

...then the red underline would have gone too far.

![2020-07-16_09-47-35_182_chrome](https://user-images.githubusercontent.com/34664007/87692627-8ff99b80-c751-11ea-9245-ee3186d20ba4.png)

The number is correct though.  There are 11 squiggles and 11 letters to underline.  So I think this means that either each red squiggle is too long or the font of the letters is not monospace.

The other issue, which is minor, is that the squiggle is a bit choppy.  For comparison, the corresponding underlying in Visual Studio is a perfectly smooth curve.

![2020-07-16_09-49-04_183_devenv](https://user-images.githubusercontent.com/34664007/87692957-fd0d3100-c751-11ea-98ec-cb56ae5b2689.png)

**Comment by loreanvictor** [comment]
I can make the squiggle actually use the same font and font-size as the default code font. Will unfortunately make the squiggle less pronounced, but should be a good compromise.

Anyways this is just a rough patch until all major browsers start properly supporting `text-decoration-style: wavy`. It has good support already, but its pretty buggy (no underline under places that don't have text, no underline under parantheses, etc.).

**Comment by loreanvictor** [comment]
deployed via `0.2.10` (also made the links behave a bit more nicely, forgot that they could get hidden behind the footer while the browser thinks they have been scrolled into view).

**Comment by bender2k14** [comment]
The scrolling links now put the line right in the center of the page.  That is great!

The underlining is now a perfectly smooth curve just like Visual Studio.  Also great!

The length change is net neutral.  I [lengthened my first underlying and shortened my second one](https://github.com/bender2k14/tyson-williams-blog/commit/040edf3e58ff7ffe1c4b971ecec1c73de9207a9b).  Here is the [live link to the second line of code](https://tysonwilliams.coding.blog/2020-07-14_identity_as_as#code9-l5).  I think it looks good like that.  Without shortening the second one, the text would be...
```
arg.Bind(t => func.Bind<Func<T, R>, R>(f => /*~err~*/f(t)/*~err~*/.As<Option<R>>()));
```

...and the output would be

![2020-07-16_12-09-31_184_chrome](https://user-images.githubusercontent.com/34664007/87701549-cb01cc00-c75d-11ea-9f9f-f4cf3f2f96f9.png)

Maybe this isn't such a big deal.  Adjusting one character left or right as I am doing is an easy workaround.
