### ISSUE TITLE
Get current URL in custom component

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#54]
Each of my blog posts contains the markdown...
> See a typo? You can fix it by editing \[this file\](https://github.com/bender2k14/tyson-williams-blog/blob/master/src/markdown/2020-07-15_naming_is_impossibly_hard.md) and then sending me a \[pull request\](https://github.com/bender2k14/tyson-williams-blog/compare).

...except that `2020-07-15_naming_is_impossibly_hard` is unique to each post.

I want to create a custom component to automate this work, but I don't know where to get that string.  Here is what I have tried.

Input:
```tsx
return <ul>
         <li>document.location.href is {document.location.href}</li>
         <li>document.location.pathname is {document.location.pathname}</li>
         <li>window.location.href is {window.location.href}</li>
         <li>window.location.pathname is {window.location.pathname}</li>
         <li>document.URL is {document.URL}</li>
         <li>document.baseURI is {document.baseURI}</li>
      </ul>
```

Output:
```
- document.location.href is about:blank
- document.location.pathname is blank
- window.location.href is about:blank
- window.location.pathname is blank
- document.URL is about:blank
- document.baseURI is about:blank
```

Am I doing this wrong or is CODEDOC not setting those values (or both!)?

**Comment by loreanvictor** [comment]
`document.location.href`, `window.location.pathname`, etc. are only set on the browser. Your **CODEDOC** code is being executed on the server (on a build server not an API server) to generate static HTML files.

You can of course make a component be rendered on the client instead of the server, where those values are defined.
```tsx
import { transport } from "@connectv/sdh/transport";

...

export function MyComponent() {
  // does client side stuff
  // like accessing document.URL
}

export const $MyComponent = transport(MyComponent);
```

Now use `$MyComponent` in your configuration (and code) instead of `MyComponent` (both need to be exported though). `$MyComponent` will act as a _transport placeholder_ on the server, not being rendered until the code reaches the browser. There, its instances on the DOM tree will be replaced with `MyComponent`, where you have access to those values.

You can read more about this [in this recipe](https://codedoc.cc/docs/customization/recipe_custom_search_api#step-1-the-search-component) or [in this blog-post](https://coding.blog/blog/jamstack).

P.s. `coding-blog-plugin` actually injects more useful values for the use-case you have in mind, so maybe use `window.source` and `window.githubConfig` instead of `document.URL`. note that these are also available on the browser only so you still need to transport your component.

**Comment by bender2k14** [comment]
Oh, sure.  I should have thought of client vs server side execution.  And I clearly I didn't read your existing recipes careful enough.

I got it working [using `window.location.pathname`](https://github.com/bender2k14/tyson-williams-blog/commit/7ee4b2e16d7c1b5fe45230e0369616ba72726f62#diff-be47e6e270cd94743d9cef769e29ffe8R11).  No parsing needed, which makes the code easy to read and understand.

> P.s. `coding-blog-plugin` actually injects more useful values for the use-case you have in mind, so maybe use `window.source` and `window.githubConfig` instead of `document.URL`.

`window.source` and `window.githubConfig` were not accessible to me in the same way as `window.location.pathname`.  Are they supposed to be accessed in a different way?

> `document.location.href`, `window.location.pathname`, etc. are only set on the browser. Your **CODEDOC** code is being executed on the server (on a build server not an API server) to generate static HTML files.
> 
> You can of course make a component be rendered on the client instead of the server, where those values are defined.

I am not particularly interested in optimizing this for the sake of the faster execution.  In principle though, it seems to me like it could be possible for a component to obtain the name of the markdown file being built on the server.

Is that currently possible?

**Comment by loreanvictor** [comment]
> Is that currently possible?

Yes, but unfortunately, through some sub-optimal methods right now:

- You can add a [post-processor](https://codedoc.cc/docs/config/page#post-processing) to add the component (which is a bit hacky and would mean the component would be added to all files in a fixed position). Post-processors do have access to the file being read.

- You can use the [`Context` component](https://github.com/CONNECT-platform/connective-html/wiki/Examples#example-theme-changer) in your [content root](https://github.com/bender2k14/tyson-williams-blog/blob/master/.codedoc/content/index.tsx), feeding any information (including the file path name, etc) to each component. I am not 100% sure if this works on server-side (so it might not work on the first run and require some debugging on [CONNECTIVE SDH](https://github.com/CONNECT-platform/connective-sdh))

The optimal method would be to:

1. Create a rendering plugin that provides these parameters to each component:
```ts
// page-address-plugin.ts
import { CompProcessPlugin, PluginPriority, ComponentThis } from '@connectv/html';

export class PageAddressPlugin<R=any, T=any> implements CompProcessPlugin<R, T> {
  priority = PluginPriority.High;
  constructor(readonly pageAddress: string) {}
  
  prepare(
    _: unknown, 
    __: unknown, 
    ___: unknown, 
    extras: { [name: string]: any; }): (result: Node) => void {
      extras.pageAddress = this.pageAddress;
      return () => {};
  }
}

export type PageAddressAwareComponentThis<R=any, T=any> = ComponentThis & {
  pageAddress: string;
};
```
2. Plug the plugin into the renderer used by `.codedoc/content/index.tsx` to render main content:
```ts
// .codedoc/content/index.tsx
// ...
import { PageAddressPlugin,  } from './page-address-plugin';

export function content(_content: HTMLElement, toc: HTMLElement, renderer: RendererLike<any, any>, file: File<string>) {
  renderer = renderer.plug(new PageAddressPlugin(file.path));
  return (...)
}
```
3. Now use the plugin in your component:
```tsx
// my-component.tsx
// ...

export function MyComponent(this: PageAddressAwareComponentThis, ...) {
  // ...
  this.pageAddress;
  // ...
}
```

However this solution, as it is evident, is involved enough to actually demand being provided by **CODEDOC** itself (I am still only holding back to come across a use-case that would need the performance, to ensure that we add a method of providing global config to components in a manner suitable for actual use-cases).

**Comment by loreanvictor** [comment]
> `window.source` and `window.githubConfig` were not accessible to me in the same way as window.location.pathname. Are they supposed to be accessed in a different way?

You do not have access to `window.githubConfig` because you have not configured your github repository in [your **CODEDOC** config file](https://github.com/bender2k14/tyson-williams-blog/blob/master/.codedoc/config.tsx) (See [this](https://codedoc.cc/docs/config/misc#github-integration) for more information).

`window.source` is available on your blog (you can open the browser console and check for yourself). These are non-standard values so will not be suggested by your editor, and you should access them by `(window as any).source` and `(window as any).githubConfig` to avoid type-checking issues.

**Comment by bender2k14** [comment]
You do not have access to `window.githubConfig` because you have not configured your github repository in [your **CODEDOC** config file](https://github.com/bender2k14/tyson-williams-blog/blob/master/.codedoc/config.tsx)

Oh, yeah....sure.

> `window.source` is available on your blog (you can open the browser console and check for yourself). These are non-standard values so will not be suggested by your editor, and you should access them by `(window as any).source` and `(window as any).githubConfig` to avoid type-checking issues.

Oh, ok.  I was previously trying to display `window.source` as though it were a `string`.  I now realize that it is an `object`, and I figured out what is inside by logging it.

Input:
```tsx
  const windowSource = (window as any).source
  console.log(windowSource)
```

Output:
```
base: "src/markdown"
namespace: ""
path: "2020-07-15_naming_is_impossibly_hard.md"
title:
  base: ""
  connector: " | "
```

**Comment by bender2k14** [comment]
> I am still only holding back to come across a use-case that would need the performance, to ensure that we add a method of providing global config to components in a manner suitable for actual use-cases.

Waiting for more use cases is a very good idea.  This might be another use case.

I noticed that all the five article cards on [my home page](https://tysonwilliams.coding.blog/) take a bit of time to fetch their data on the client.  The URL in each article card is to another page in the same site...built by **CODEDOC** "at the same time" as the current page.  In theory, this information is available on the server.

Maybe the article card could be optimized with behavior that depends on the provided URL.  If the URL is to another page in the same site built by **CODEDOC** "at the same time", then all the desired information is collected on the server.  Otherwise, the URL is to a page on a different site, and the desired information is obtained on the client using the current behavior of the article card.

**Comment by loreanvictor** [comment]
Actually, on article cards, the information is not necessarily available. Imagine you have two articles referencing each other using Article cards, both either being built for the first time or their hero image / title / etc changing in the current build. Trying to resolve this information on the server side would only be possible by a deferred two-pass rendering which is too much added complexity for minor performance gain.
