### ISSUE TITLE
Always open left drawer when space available

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#58]
On the desktop, the list of headings is might or might not be visible when viewing on a desktop.  If there is enough space, then it is visible.  If there is not enough space, then it is removed.  I think this behavior is great.  Here is an example where it is visible.

![2020-07-27_08-38-15_200_chrome](https://user-images.githubusercontent.com/34664007/88550300-09fa1200-cfe7-11ea-8f2d-736403f0654e.png)

I often find myself frequently opening and closing the left draw that contains the table of contents even though I am on a desktop and zoomed out far enough that it would be ok to left the draw open.  So why do I keep closing it?  I don't know.  I think it is partially a subconscious process.  It can be closed, and I am finished using it, so it should be closed.  I certainly know that I close more draws and turn off more lights in my house than anyone else.

Can the left drawer that contains the table of contents stay open on desktop when zoomed out far enough?

Here is a [site](https://www.temporalcohesion.co.uk/) that has the kind of behavior that I am talking about.

**Comment by loreanvictor** [comment]
it sort of does that. it becomes a full-screen thingy when there isn't enough space, and a left-leaning drawer when there is.

about closing it, I would recommend keeping it closable, in case some user wants to get it out of the way (I personally always do). this means the question boils down to default, [which you can easily override by changing one line](https://codedoc.cc/docs/customization/recipe_toc_state#code1-l23).

> o why do I keep closing it? I don't know. I think it is partially a subconscious process. It can be closed, and I am finished using it, so it should be closed.

tbh I kept the default (despite some requests for changing it) for that very same reason. I keep closing it, I feel stuff at my screen are more cleanly when it is closed, and now I am slowly getting more and more bothered by other documentation tools and websites for not providing the option of closing the left-side navigation bar.
