### ISSUE TITLE
Crash-to-homescreen when viewed on Chrome on Android

### ISSUE THREAD

**Issue by fergalt** [CONNECT-platform/codedoc#6]
On both codedoc.cc, and coding.blog, after scrolling down for a few seconds, Chrome spontaneously crashes to the homescreen without error message. There is a brief blackscreen before the home screen appears. 

Galaxy S6 
Android 6.0.1
Chrome 79.0.3945.136.

This does not happen on any other site with this device.

**Comment by mikaelmello** [comment]
In case it helps, it is not happening on my device.

Moto G (5S) Plus
Android 8.1.0
Chrome 81.0.4044.117

**Comment by loreanvictor** [comment]
@fergalt could you try the following links on your device to see if any of them results in a similar crash?

[https://codepen.io/robinrendle/full/LmzLEL](https://codepen.io/robinrendle/full/LmzLEL)
[https://codepen.io/netsi1964/full/JqBLPK](https://codepen.io/netsi1964/full/JqBLPK)
[https://codepen.io/pepf/full/GqZkdj](https://codepen.io/pepf/full/GqZkdj)
[https://codepen.io/SitePoint/full/xRpvzX](https://codepen.io/SitePoint/full/xRpvzX)

**Comment by fergalt** [comment]
Yes. It takes much more effort, but I managed to provoke the final link
into an identical crash, by quickly and repeatedly alternating between
clicking on the picture, then clicking outside the picture, interrupting
the transition.

Similar to the experience on the coding.blog and codedoc, I notice it begin
to stutter before it briefly seems to recover, then it crashes.

The first three worked fine, in spite of my best efforts to provoke it. No
slowdowns at all with repeated scrolling.

**Comment by loreanvictor** [comment]
@fergalt then could you (or anyone who can reproduce the issue) please create an issue on [chrome bug tracker](https://bugs.chromium.org/p/chromium/issues/list) for this and link it here?

**Comment by fergalt** [comment]
Done! https://bugs.chromium.org/p/chromium/issues/detail?id=1077113

**Comment by loreanvictor** [comment]
@fergalt thanks a lot! will keep the issue open to track what happens with chrome and make changes if necessary.

**Comment by loreanvictor** [comment]
closing this issue since there pending issue is closed due to inactivity.
