### ISSUE TITLE
Recommended markdown to center an image

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#60]
I think the images included in my blog posts look better when centered (horizontally).

Is there do this in markdown syntax without using HTML?

Now that I have been [reminded that HTML is also valid markdown](https://github.com/CONNECT-platform/coding-blog-plugin/issues/12#issuecomment-665042652), I just centered my images (in [this commit](https://github.com/bender2k14/tyson-williams-blog/commit/51e6d291861c605ff1b60cfb3876cd868118dbbe)) by using HTML like
```HTML
<img src="path_to_file"
     alt="alt text"
     style="display: block; margin-left: auto; margin-right: auto;">
```

Looking at [one of my blog posts with an image](https://tysonwilliams.coding.blog/2020-07-29_everything#windows-file-explorer), this seems to work...even though I don't set the `style` argument `width` to `50%`, which [W3Schools claims is necessary](https://www.w3schools.com/howto/howto_css_image_center.asp).

**Comment by loreanvictor** [comment]
I have seen this happening for text (quoted text specifically) on some blogs on `coding.blog` as well. I suspect the use-case is really mostly blogging and not general documentation, so I think the best solution would be [a small component in `coding-blog-plugin`](https://github.com/CONNECT-platform/coding-blog-plugin/issues/14).
