### ISSUE TITLE
Disambiguate heading interactions on desktop

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#65]
This is a spin of #57.

The following is nearly a quote of https://github.com/CONNECT-platform/codedoc/issues/57#issuecomment-674959501.

If I long press a word in a heading on mobile, then the word is highlighted, a menu appears, and I can select "Copy" to copy. In the process, the link to the heading is not copied. That is all as expected.

Here is the equivalent workflows on a desktop. They are given in order of fastest to slowest. Unfortunately, only the slowest one currently works.

1. Double left-click a word in a heading.  The word is temporarily highlighted but then is unhighlighted.  Also, the link to the heading is copied twice.
2. Click and drag across a word in a heading to highlight it.  Right-click to open the menu containing the option to copy.  The menu does not appear, the word is unhighlighted, and the link to the heading is copied.
3. Click and drag across a word in a heading to highlight it.  Use `Ctrl+C` to copy the highlighted word.

You did a great job differentiating touch interactions on mobile to distinguish copy link vs copy text behavior (c.f. #57).  For desktop, can you similarly differentiate single- vs double-click to get (1) to work and left- vs right-click to get (2) to work?

**Comment by loreanvictor** [comment]
deployed via `0.2.14`

**Comment by bender2k14** [comment]
It all works perfectly!  Great job :D

**Comment by loreanvictor** [comment]
> It all works perfectly! Great job :D

Its all thanks to your great feedback!
