### ISSUE TITLE
Footnote Component

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/codedoc#67]
Summary: footnotes are useful and easy to add. They can be useful in all manners of programming/tech-related writing, including blogs and software documentation.

This is a preview of proposed syntax:

```md
This is paragraph one [This is footnote one](:Footnote).

This is paragraph two [](:Footnote (id=something))

> :Footnote id=something
>
> This is footnote two (and [here](https://google.com) is also a link).

> :Footnotes
```

This would incorporate:
- an inline component and a quoted component (for more involved footnote text), linkable with internal IDs
- a `Footnotes` component (for placement of footnotes)
- a post-processor for gathering footnotes and rendering them (statically)

Original discussion can be viewed [here](https://github.com/CONNECT-platform/coding-blog-plugin/issues/19).

**Comment by TysonMN** [comment]
I also love when it is possible to use a hyperlink to go from each footnote back to where the incoming link was.  See [this blog post](https://www.hillelwayne.com/equals-as-assignment/) as an example of this functionality.

**Comment by loreanvictor** [comment]
will be deployed via `@codedoc/core@0.2.15`.

**Comment by loreanvictor** [comment]
> I also love when it is possible to use a hyperlink to go from each footnote back to where the incoming link was. See this blog post as an example of this functionality.

Also @TysonMN although originally I liked the idea for its usability, I didn't end up implementing it in this first iteration. Reasons being:

- It is unclear which note should you return to, in case multiple points reference the same foot note (which they can)
- You get the same functionality with browser's back button (which seems to be working fine on Chrome, Safari and Firefox)

**Comment by TysonMN** [comment]
Those are good reasons.  Thanks for the great work.  I can't wait to test! :)

**Comment by loreanvictor** [comment]
published via `@codedoc/core@0.2.15`

**Comment by TysonMN** [comment]
Works great.  I am excited to start using this in one of my draft posts.  Thanks! :)

**Comment by loreanvictor** [comment]
thanks for the suggestion!
