### ISSUE TITLE
Google Analytics with newer script

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#68]
I am trying to add Google Analytics to my site.  I see how [the documentation suggests to define a Google Analytics plugin](https://codedoc.cc/docs/config/plugins#writing-a-plugin), but Google told me to copy-paste code that isn't the same as in that documentation.  Here is the code Google told me to copy.

```HTML
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXX-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-XXXX-1');
</script>
```

By looking at the previous documentation and looking at [this documentation for Google's data layer](https://developers.google.com/tag-manager/devguide), I wrote this code.
```tsx
export function googleAnalytics(gaCode: string) {
  let url = `'https://www.googletagmanager.com/gtag/js?id=UA-${gaCode}-1'`
  function addToDataLayer() {
    let newData = [{
      'js': new Date(),
      'config': `'UA-${gaCode}-1'`
    }];
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push(newData);
  }
  return function(): ConfigOverride {
    return {
      page: {
        scripts: [
          <script async src={url}></script>,
          <script>{addToDataLayer()}</script>
        ]
      }
    }
  };
}
```

I think this is nearly correct, but I don't know how to deal with `window.dataLayer` not being on defined on the type `Window`.

![2020-08-29_14-17-00_273](https://user-images.githubusercontent.com/34664007/91644538-84f98280-ea02-11ea-9809-6157be5b523a.png)

**Comment by loreanvictor** [comment]
> I see how the documentation suggests to define a Google Analytics plugin

I feel like I should note that its not the recommended way of using Google Analytics, its just an example for writing plugins. However, if you are going to write a plugin, I would highly encourage you to write a more generic and reusable one so that other CODEDOC users can also use it.

> I think this is nearly correct, but I don't know how to deal with window.dataLayer not being on defined on the type Window.

Simply use `(window as any)` anytime you want to access `dataLayer`. There are of course cleaner options (like defining an extended window type and casting to that in scopes you want to access `dataLayer`) as well, though I don't think its worth going through the trouble.

**Comment by bender2k14** [comment]
Thanks for all this information and especially for your edit to point out that I was incorrectly using `addToDataLayer`.

I think I understand the syntax now.  The code is contained in strings as JavaScript that is sent to the client for execution.  I don't need casts in that code.

> Also I should note that the naive method of integrating Google Analytics would only capture the event of someone landing on a page and not them navigating between pages, since navigation between different CODEDOC pages would not cause a page reload (so no new event sent to Google Analytics). You can send GA events on page navigations besides the initial load by listening to `"navigation"` event on `window` object, i.e. `window.addEventListener("navigation", ...);`

I verified with [Google's Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en) that analytics is basically working on [my site](https://tysonwilliams.coding.blog/).  However, I don't think the navigation is working.  I did a recording as shown in [this video](https://www.youtube.com/watch?v=EkNsaBDT8Cc), but when I stopped the recording, the Tag Assistant Report tab only contains one entry for the "page" currently being viewed and the Google Analytics Report tab is empty.

Here is the code I am using.
```tsx
export function googleAnalytics(trackingId: string) {
  let url = `https://www.googletagmanager.com/gtag/js?id=${trackingId}`
  let functionName = 'storeAnalyticsForGoogle'
  let functionBody =
    `window.dataLayer.push([{ 'js': new Date(), 'config': '${trackingId}' }]);`
  let pushToDataLayer =
    'window.dataLayer = window.dataLayer || [];' +
    `function ${functionName}(){${functionBody}}` +
    `${functionName}();`
  let addNavigationListener =
    `window.addEventListener("navigation", ${functionName});`
  return function(): ConfigOverride {
    return {
      page: {
        scripts: [
          <script async src={url}></script>,
          <script>{pushToDataLayer}</script>,
          <script>{addNavigationListener}</script>
        ]
      }
    }
  };
}
```

> ...if you are going to write a plugin, I would highly encourage you to write a generic and reusable one (and publish it perhaps to NPM) so that other CODEDOC users can also use it.

Sure, I am up for that.  I have never done this before though.  How should I start?  Create a repo?  How should I name it?  If this were a .NET NuGet package, I might name it `Coding.Blog.Plugins.GoogleAnalytics`.

**Comment by loreanvictor** [comment]
I haven't worked with GA for quite some time now, so I might be wrong. But I was expecting something that would retrieve current URL and send it as a special event to GA, i.e. something [like this](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications).

Also "`" strings can be multiline, so perhaps using one string template might make the code a bit more readable. You can even add it all directly to one `<script>` body. I would recommend this since I would also recommend wrapping the defined function (and all of the code) inside the scope of an anonymous function that you call instantly, to avoid having name collisions on the function:

```tsx
<script>{`
(function(){
  function storeAnalyticsForGoogle() {
    // ...
  };

  window.dataLayer = window.dataLayer || [];
  storeAnalyticsForGoogle();
  window.addEventListener("navigation", storeAnalyticsForGoogle);
})();
`}</script>
```

> Sure, I am up for that. I have never done this before though. How should I start? Create a repo? How should I name it? If this were a .NET NuGet package, I might name it Coding.Blog.Plugins.GoogleAnalytics.

I suspect [this repository](https://github.com/CONNECT-platform/coding-blog-plugin) should also act as a nice template on that front. I think the typical convention is something like `codedoc-google-analytics` for NPM packages, and its a good idea to name the repo the same as the package so that people can find the code easily on GitHub (though it is typically linked on NPM too).

**Comment by bender2k14** [comment]
> `""` strings can be multiline, so perhaps using one string template might make the code a bit more readable.

I noticed that, but then those spaces also appear in the `<script>` tag.  I don't normally care to optimize things like this by sending the fewest characters, but I don't mind this compromise of adding the strings together during the build.

> You can even add it all directly to one `<script>` body.

Yes.  I woke up Sunday morning and had this exact thought.

> I would recommend this since I would also recommend wrapping the defined function (and all of the code) inside the scope of an anonymous function that you call instantly, to avoid having name collisions on the function

Yes, good idea.  I thought about the possibility of a name collision but didn't know what I could do to help avoid it.

> I haven't worked with GA for quite some time now, so I might be wrong. But I was expecting something that would retrieve current URL and send it as a special event to GA, i.e. something [like this](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications).

I think I have GA working correctly now on [my site](https://tysonwilliams.coding.blog/).

Instead of directly using `analytics.js` like in the documentation you linked, [Google recommended using `gtag.js`](https://developers.google.com/analytics/devguides/collection/upgrade#web) via [this code](https://developers.google.com/analytics/devguides/collection/gtagjs#install_the_global_site_tag) that I also shared in https://github.com/CONNECT-platform/codedoc/issues/68#issue-688590373.  The only change I made, as you suggested, was to also execute the calls to `gtag` on each `navigation` event.

> I suspect [this repository](https://github.com/CONNECT-platform/coding-blog-plugin) should also act as a nice template on that front. I think the typical convention is something like `codedoc-google-analytics` for NPM packages, and its a good idea to name the repo the same as the package so that people can find the code easily on GitHub (though it is typically linked on NPM too).

Great name.  I created [the repository](https://github.com/bender2k14/codedoc-google-analytics).

I looked at your `coding-blog-plugin` repository (and I see the GitHub action that deploys the latest documentation), but how do you publish a new version of that plugin?  Is automating this task one of the devops improvements that you said could be made?

**Comment by loreanvictor** [comment]
it can be. right now I push, test, if everything works, I will bump the version and push (typically via a commit called `bump version`), and then `npm publish`. this can be further automated of course, but its not much of a hassle (or particularly error-prone) to demand an automated workflow.

**Comment by bender2k14** [comment]
I have written up all my thoughts [here](https://github.com/bender2k14/codedoc-google-analytics/blob/master/Documentation_of_Correctness.md) about why I think my code to communicate with Google Analytics from a CODEDOC site is correct.

Thanks for all your help @loreanvictor :)
