### ISSUE TITLE
Support F# style comments for code-snippet features

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#71]
I originally asked for Error underline support in #49.  [This feature](https://codedoc.cc/docs/code/highlights#errorwarning-underline) now exists for languages in which `/*~*/` is a valid comment.  That worked when I created #49 because I wanted to add error underlying for C#, and I am now using that feature in [this post](https://tysonwilliams.coding.blog/2020-07-14_identity_as_as).

Now I want to use error underlying for F# in [this post](https://tysonwilliams.coding.blog/2020-09-21_bottom_type_in_fsharp).  Block comments in F# look like `(*~*)` instead of `/*~*/`.

**Comment by loreanvictor** [comment]
Makes perfect sense. Fortunately F# uses the same single-line comment syntax as C, so the only feature that would need some adaptation would be the underlines.

**Comment by loreanvictor** [comment]
not deployed yet, will deploy via `@codedoc/core@0.2.15`

**Comment by loreanvictor** [comment]
published via `@codedoc/core@0.2.15`

**Comment by TysonMN** [comment]
Works great.  Thanks! :)
