### ISSUE TITLE
Snippet to be run in terminal

### ISSUE THREAD

**Issue by uloco** [CONNECT-platform/codedoc#76]
Is there a way to add code snippets, where it is clear to the user, that it is needed to be run in a terminal? Normally I would just prefix it with a $-sign, but this way codedoc copies it also when clicked. Maybe we could strip that away, or make a custom terminal config for snippets where the $ sign is prepended but not selectable/copied on click.

**Comment by TysonMN** [comment]
I second this.  I prefixed with a $-sign in [this example](https://tysonwilliams.coding.blog/2020-07-13_process_explorer#use-process-explorer) but am not in love with it.

**Comment by loreanvictor** [comment]
this is a nice idea, but lets try to get the requirements clarified:

- there should be a prefix character / string on each line, which is not copied.
- there should be a way to exempt some lines from this (and perhaps generally give them a different view so it is more clear they are _results_ or something).
- perhaps some default prefix for easier / consistent configuration (like `$` being the default, overridable per snippet or maybe even via the theme)

am I missing something?

also generally examples of nice _terminal snippets_ you've seen out there would help with the design / requirements of this.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.16`

**Comment by TysonMN** [comment]
Works great!  Thanks :)
