### ISSUE TITLE
Theme shadow is not applied

### ISSUE THREAD

**Issue by uloco** [CONNECT-platform/codedoc#78]
The shadow property is not used, no matter what I put in there.

**Comment by loreanvictor** [comment]
could you provide more context? like where have you tried to put it and to what value you wanted to set it? because generally speaking [it seems to work](https://loreanvictor.github.io/rxdeep/) ([theme file](https://github.com/loreanvictor/rxdeep/blob/master/.codedoc/theme.ts))

**Comment by uloco** [comment]
"none" works, because as soon as you put a color or anything in shadow it will disappear completely. I tried it in chrome and safari. I put in `"red"` or `"#ff0000"`, in `.codedoc/theme.ts`

**Comment by loreanvictor** [comment]
yes, as mentioned [here](https://codedoc.cc/docs/theme#code6-l4) it should be a `CSS box-shadow string`, and `"red"` or `"#ff0000"` are not (something like `0 2px 6px red` should work).
