### ISSUE TITLE
Deployment on Vercel

### ISSUE THREAD

**Issue by cupcakearmy** [CONNECT-platform/codedoc#80]
Hi

I wanted to ask if there a solution for hosting it on Vercel. The problem is that Codedoc generates files: `docs/some.md` -> `dist/some.html` whereas for vercel I would need `dist/some/index.html`

Is there any way to achieve this? Thanks! ❤️

**Comment by cupcakearmy** [comment]
Solved it

You can add `vercel.json` in the root of the project and it will work on vercel.
```
{
  "cleanUrls": true
}
```
I thing it would be a nice addition into the docs 🙂
Feel free to close

**Comment by loreanvictor** [comment]
Perfect! I personally have to look at vercel docs first, but its definitely a good idea to add a small section to the docs. You can (if you want to) even create a PR to [this repo](https://github.com/CONNECT-platform/codedoc-docs) for enriching the docs.

**Comment by cupcakearmy** [comment]
@loreanvictor  I've made a PR 🙂

**Comment by im-coder-lg** [comment]
After adding `vercel.json`, what should you do?
