### ISSUE TITLE
Horizontal whitespace

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#83]
Shortly after [this line of code](https://tysonwilliams.coding.blog/2020-12-01_csharp_task_to_fsharp_async#code8-l27) in my recent blog post, I have two images next to each other.  I wanted them both centered, but I also wanted horizontal space between them.

I added some number of non-breaking spaces until I thought it looked good enough.  That source is available [here](https://github.com/TysonMN/tyson-williams-blog/blame/master/src/markdown/2020-12-01_csharp_task_to_fsharp_async.md#L346-L348).

Is there a better way to add horizontal whitespace?

**Comment by loreanvictor** [comment]
Similar to [this](https://github.com/CONNECT-platform/codedoc/issues/84#issuecomment-736838470), I think the idiomatic way of achieving something like that in pure markdown is using tables:

```md
| ![left-image][1] | &emsp;&emsp; | ![right-image][2] |
| :--------------: | ------------ | :---------------: |
| C# output        |              | F# output         |

[1]: https://tysonwilliams.coding.blog/src/assets/images/cancellation_wait_wait_canceled.gif
[2]: https://tysonwilliams.coding.blog/src/assets/images/cancellation_wait_canceled_wait.gif
```

| ![left-image][1] |&emsp;  | ![right-image][2] |
| :--------------: | --- |:---------------: |
| C# output        |     | F# output         |

[1]: https://tysonwilliams.coding.blog/src/assets/images/cancellation_wait_wait_canceled.gif
[2]: https://tysonwilliams.coding.blog/src/assets/images/cancellation_wait_canceled_wait.gif

Also for lots of space, perhaps `&emsp;` is more comfortable than `&nbsp;`.

- For a markdown-ish solution, I can recommend [custom components](https://codedoc.cc/docs/markdown/custom-components)
- Custom HTML with inline styling should also work fine.
- Using the [formula component](https://codedoc.cc/docs/markdown/formula) also provides access to Tex which gives great control over distancing and formatting, though I am not sure how it would look like in this case.

**Comment by TysonMN** [comment]
> Also for lots of space, perhaps `&emsp;` is more comfortable than `&nbsp;`.

Although replacing `&nbsp;` with `&emsp;` is essentially the same solution, it is much more palatable.

I will consider that improvement good enough and ask my other table questions in #84.
