### ISSUE TITLE
Missing ts-node-dev

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#85]
Yesterday I helped my friend @dharmaturtle locally host my blog on his Windows computer.  I had him follow [the steps that I list as essential](https://github.com/TysonMN/tyson-williams-blog#essential), which are to execute the commands
```
npm i -g @codedoc/cli
codedoc install
codedoc serve
```

Everything seemed to work until he executed `codedoc serve`.  I don't have his exact error message, but it was similar to [this problem that I have had before](https://github.com/CONNECT-platform/codedoc/issues/59#issuecomment-664634572) but with `ts-node-dev` instead of `ts-node`, so his error message was something like
```
SomePath> codedoc build

# Building ...
# Fetching project configuration ...
`ts-node-dev` is not a recognized as an internal or external command, operable program or batch file.
# Build Failed.
```

I don't remember exactly, but I think we overcame this by executing
```
npm i -g @ts-node-dev
```

**Comment by loreanvictor** [comment]
`ts-node-dev` should get installed as a local dependency of the CLI. The CLI then adds `<where-global-node-modules-are>/@codedoc/cli/.node_modules/.bin/` to the PATH of every child process it spawns. on that note, it would be extremely helpful if you could check that sub-directory and see if `ts-node-dev` is locally installed (same with `ts-node`, as I suspect it is used at an earlier setup step).

**Comment by dharmaturtle** [comment]
`ts-node-dev` and `ts-node` exist in that folder. I do not know if that necessarily means they're installed.

![image](https://user-images.githubusercontent.com/1278803/100809729-6e493a00-33fc-11eb-91f1-0063497ebb23.png)

**Comment by loreanvictor** [comment]
p.s. @dharmaturtle could I ask which terminal emulator do you use? and does the issue persist in default command prompt as well? I am trying to understand whether this is the same issue as [this](https://github.com/CONNECT-platform/codedoc/issues/97).

**Comment by dharmaturtle** [comment]
Probably just `cmd.exe`. The original 3 commands now work for me....

```
npm i -g @codedoc/cli
codedoc install
codedoc serve
```

as whatever Tyson and I did in December fixed it. Notably the following command fails:

```
C:\Code\tyson-williams-blog-private>npm i -g @ts-node-dev
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@ts-node-dev": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by loreanvictor** [comment]
yes I think the correct version of that would be the following:

```bash
npm i -g ts-node-dev
```

(i.e. without the `@`).

ok so I'll be closing this issue as there is a similar issue open right now. if you find any new information feel free to re-open this one.
