### ISSUE TITLE
parsing component content as js code

### ISSUE THREAD

**Issue by nakednous** [CONNECT-platform/codedoc#88]
How to parse my component `content` var as plain js code without html tags (so that the blocks gets executed as a script)? So far I tried:

```js
<script> ${content} </script>
```
see [this line](https://github.com/objetos/p5.quadrille.js/blob/pages/.codedoc/components/p5/index.tsx#L64), but I got:

```html
<script> [object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement] </script>
```

See an [example page](https://github.com/objetos/p5.quadrille.js/blob/pages/docs/md/docs/p5-iframe.md) and its [result](https://objetos.github.io/p5.quadrille.js/docs/p5-iframe).

**Comment by loreanvictor** [comment]
I did not fully understand what you want to do here. As you can see, `content` parameter is an array of DOM nodes (which are the children passed to the component). If you want to turn it into HTML string, I would recommend something like this:

```tsx
const htmlString = (<div>{content}</div>).innerHTML;
```

**Comment by nakednous** [comment]
Yeah that's what I meant. Have tried:

```js
let code: string = (<div>{content}</div>).innerHTML;
code = code.replace(/<\/?[^>]+(>|$)/g, "");
```

which also worked, but your solution is simpler. Thanks!
