### ISSUE TITLE
/*~err~*/ comments for code-snippet error underlying feature missing since CODEDOC 0.2.15

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#89]
The Error/Warning Underline feature (requested in issue #49 and [documentation here](https://codedoc.cc/docs/code/highlights#errorwarning-underline)) was added in `codedoc/core` 0.2.9.  Support was later added for block comments `(* *)` (requested in issue #71) in `codedoc/core` 0.2.15.

Unfortunately, `codedoc/core` 0.2.15 also removed support for `/* */` comments.  I determined this by testing before and after [this commit](https://github.com/TysonMN/tyson-williams-blog/commit/a4835179f7487428b4e970e9ec6b91c0b8d70d99) in which I only upgraded from 0.2.14 to 0.2.15 and checking the locally hosted version of [this line on my live site](https://tysonwilliams.coding.blog/2020-07-14_identity_as_as#code6-l1).  The regression still exists in the latest version, which is 0.2.19.

Since [the documentation for the Error/Warning Underline feature](https://codedoc.cc/docs/code/highlights#errorwarning-underline) shows working examples using `/* */` comments, this tells me that the site was deployed using 0.2.14 or earlier.  At the same time, the source code for the CODEDOC docs has `codedoc/core` at version 0.2.19.  This makes me want there to be an easy way to know which version of dependencies like `codedoc/core` and `codedoc/coding-blog-plugin` were used when creating a CODEDOC site.  To that end, here is a (crazy?) idea.  What if every CODEDOC site included a page at (say) `urlBeginning/codedoc_dependencies` that shows the contents of the `dependencies` section of the `package.json` file.  Here is that section for [CODEDOC docs](https://github.com/CONNECT-platform/codedoc-docs/blob/2b1aa5fb10ab01012548d18bb7b7fd438390642c/.codedoc/package.json#L2-L4) and [my blog](https://github.com/TysonMN/tyson-williams-blog/blob/bbb7846d3d9eb0f6bb36edb71a913ce3f7a9b315/.codedoc/package.json#L2-L5).

More practically, can the [the documentation for the Error/Warning Underline feature](https://codedoc.cc/docs/code/highlights#errorwarning-underline) be improved by adding an example that uses `(* *)`?  Then the examples would include uses of both `/* */` and `(* *)`, and I could point out the regression to `/* */` there instead of having to use my blog.

**Comment by TysonMN** [comment]
> I am sorry I didn't understand your proposal. [This line](https://github.com/CONNECT-platform/codedoc-docs/blob/2b1aa5fb10ab01012548d18bb7b7fd438390642c/.codedoc/package.json#L3) shows that codedoc website was built using 0.2.19, as any push to master always gets deployed automatically.

That's ok.  I think your raised a good point.  It is typically sufficient to look at the `dependencies` section in the `package.json` file in the corresponding repository of the CODEDOC site in question, so I don't think my (unclear) proposal is worth considering.

**Comment by TysonMN** [comment]
I figured out the problem.  I was trying to achieve the error underlining via `/*~err~*/` while the CODEDOC documentation is using `/*~*/`.  I see the documentation doesn't mention `/*~err~*/` (anymore?).

Did you intentionally remove support for the `/*~err~*/` syntax?

I prefer `/*~err~*/` over `/*~*/` for the purpose of readability, but I can be content with `/*~*/`.

**Comment by loreanvictor** [comment]
> Did you intentionally remove support for the `/*~err~*/` syntax?

No this is a bug, I'll deploy the fix right away.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.20`

**Comment by TysonMN** [comment]
Perfect.  That fix works.

You are so quick! :D

And such an easy fix too.  It makes me think that I could have figured it out myself.  I like finding such sources of confidence when the alternative is to give up before even trying :)

**Comment by loreanvictor** [comment]
it was a typo really, I think `/*~err*/` would have worked 😅😅
